# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody_reagent',
            name='concentration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='antibody_reagent',
            name='manu_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='antibody_reagent',
            name='tests_per_vial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='antibody_reagent',
            name='volume_per_test',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='antibody_reagent',
            name='volume_per_vial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
