# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20161107_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antibody_reagent',
            name='tests_per_vial',
        ),
    ]
